[metadata]
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Topic :: Security
    Topic :: Software Development :: Testing
description = Common config for Sentry for Fuzzing tools
keywords = fuzz fuzzing security test testing
license = MPL 2.0
license_files = LICENSE.md
long_description = file: README.md
long_description_content_type = text/markdown
maintainer = Mozilla Fuzzing Team
maintainer_email = fuzzing@mozilla.com
name = moz-sec-sentry
platforms = any
url = https://github.com/MozillaSecurity/sentry

[options]
install_requires =
    psutil
    sentry-sdk >= 1.44.0
package_dir =
    = src
packages =
    moz_sec_sentry
zip_safe = False
python_requires = >=3.9

[options.extras_require]
dev =
    pre-commit
    tox

[options.package_data]
moz_sec_sentry =
    py.typed
